### PR TITLE
chore(nixpkgs-stable): move to a new 23.05 nixpkgs

### PR DESCRIPTION
**Pull request by selfuryon**
Try to update nixpkgs to 23.05 channel

### CODE REVIEW

**Comment by selfuryon** [comment]
Strange things with nethermind =\

**Comment by selfuryon** [comment]
@aldoborrero can you check please `nethermind` deps? I see you added this package, so maybe you will be able to fix that, but my approach with `dotnet restore` and after `nuget-to-nix` doesn't work right now dunno why

**Comment by aldoborrero** [comment]
@selfuryon yes, I'll have a look today

**Review by aldoborrero — APPROVED** [review]
LGTM

**Comment by aldoborrero** [comment]
@selfuryon improved the situation for updating `nuget-deps` for `nethermind`.

**Pull request merged**
