### PR TITLE
chore: update wake and switch to nixpkgs 23.11

### LINKED ISSUE #421: Problem with `update flake packages` action
### Context

We can't run `Update Flake Packages`: https://github.com/nix-community/ethereum.nix/actions/runs/7293705740

### Bug description

The problem in that we can't run `nix flake show`. Need to investigate

### Steps to reproduce

`nix flake show`

### Before submitting

- [X] I have attached links to [the documentation](https://nix-community.github.io/ethereum.nix), and possibly related [issues](https://github.com/nix-community/ethereum.nix/issues) and [discussions](https://github.com/nix-community/ethereum.nix/discussions).

### PR DESCRIPTION
**Pull request by selfuryon**
I did:
* update wake to the latest version
* switch to the latest stable nixpkgs version (poetry2nix doesn't work with `23.05` https://github.com/nix-community/poetry2nix/issues/1422)

I also need to instantiate `poetry2nix.mkPoetryApplication`, but I can't. I hope it close #421

### CODE REVIEW

**Comment by selfuryon** [comment]
But like that it works fine: https://github.com/nix-community/poetry2nix/blob/master/templates/app/flake.nix#L18

**Comment by catwith1hat** [comment]
@selfuryon I have a competing unfinished commit to update to nixpkgs-23.11. Here is what I found:
* lighthouse doesn't build on 23.11 because Rust is too new. That's because of lighthouse depending on an old version of libmdbx-rs in its slasher Cargo.tomb. I "solved" this by introducing a nixpkgs_2305 input and just having lighthouse stay behind. * ssvnode: My fix is exactly like yours.
* I haven't fixed Nimbus yet in my commit.
Just FYI.

**Comment by selfuryon** [comment]
> @selfuryon I have a competing [unfinished commit](https://github.com/catwith1hat/ethereum.nix/commit/75ad3f8926a413cc2e2a37db234ee45fa2923612) to update to nixpkgs-23.11. Here is what I found:
> 
>     * lighthouse doesn't build on 23.11 because Rust is too new. Lighthouse depends on an old version of libmdbx-rs in its slasher Cargo.tomb, and that old libmdbx-rs in turn points to an old bindgen library. The old bindgen dependency chokes on an LLVM dependency update like [this](https://github.com/rust-lang/rust-bindgen/issues/2312). bindgen would need to be updated inside sipg's fork of libmdbx-rs. But I am not going to touch that to be frank. I "solved" this by introducing a nixpkgs_2305 input and just having lighthouse stay behind.
> 
>     * ssvnode: My fix is exactly like yours. Just my override is inside packages/default.nix.
> 
>     * I haven't fixed Nimbus yet in my commit.
>       Just FYI.

For the first point seems related this one: https://github.com/sigp/lighthouse/issues/4280. Maybe we can just disable slasher feature for now to mitigate that. I will try

**Comment by selfuryon** [comment]
Good, switch to `slasher-lmdb` (it's enabled by default) helps

**Comment by selfuryon** [comment]
The only problem that `poetry2nix.mkPoetryApplication` still is the derivation, idk how to fix that

**Comment by catwith1hat** [comment]
> The only problem that poetry2nix.mkPoetryApplication still is the derivation, idk how to fix that

My approach was to [also add the poetry2nix overlay](https://github.com/catwith1hat/ethereum.nix/commit/75ad3f8926a413cc2e2a37db234ee45fa2923612#diff-206b9ce276ab5971a2489d75eb1b12999d4bf3843b7988cbe8d687cfde61dea0L104-L107) to `pkgs` 
```
          pkgs = lib.extras.nix.mkNixpkgs {
            inherit system;
            inherit (inputs) nixpkgs;
+            overlays = [inputs.poetry2nix.overlays.default];
          };
```
This made my `nix flake check` pass.

**Comment by selfuryon** [comment]
> > The only problem that poetry2nix.mkPoetryApplication still is the derivation, idk how to fix that
> 
> My approach was to [also add the poetry2nix overlay](https://github.com/catwith1hat/ethereum.nix/commit/75ad3f8926a413cc2e2a37db234ee45fa2923612#diff-206b9ce276ab5971a2489d75eb1b12999d4bf3843b7988cbe8d687cfde61dea0L104-L107) to `pkgs`
> 
> ```
>           pkgs = lib.extras.nix.mkNixpkgs {
>             inherit system;
>             inherit (inputs) nixpkgs;
> +            overlays = [inputs.poetry2nix.overlays.default];
>           };
> ```
> 
> This made my `nix flake check` pass.

Is `nix flake show` also works fine without `--allow-import-from-derivation`?

**Comment by catwith1hat** [comment]
> Is `nix flake show` also works fine without `--allow-import-from-derivation`?

No, but `nix flake show` doesn't work either on the current main branch.

**Comment by selfuryon** [comment]
> > Is `nix flake show` also works fine without `--allow-import-from-derivation`?
> 
> No, but `nix flake show` doesn't work either on the current main branch.

Yeah, but with `flake-utils` with the same style it works, I just wanted to fix that, but maybe it would be easy to fix a script for nix-update.

@brianmcgee @aldoborrero can you pls check this PR and approve it?

**Review by brianmcgee — APPROVED** [review]
Lgtm

**Pull request merged**
