### PR TITLE
feat: introduction of devshell

### PR DESCRIPTION
**Pull request by aldoborrero**
This PR introduces [`devshell`](https://github.com/numtide/devshell) rather than using `mission-control`

### CODE REVIEW

**Review by selfuryon — DISMISSED** [review]
LGTM, but just curious, why not devenv or similar projects?

**Comment by aldoborrero** [comment]
@selfuryon I chose `devshell` as it's quite similar to `mission-control` but removes extra mambo jambo that regular `mkShell` introduces into the system variables when loading the dev environment.

And why not `devenv`? Mostly it's a personal preference, I do believe it introduces too much that, probably, we won't need in the near term. We don't need features like processes, languages, containers, etc. Even if we do someday, I prefer to incorporate more fine-grained tools like [`process-compose`](https://github.com/F1bonacc1/process-compose) or another similar tooling. I prefer to favor the Unix philosophy (do one thing very well).

Also with `devshell` I can optimize the repository much faster if necessary as I'm working with Numtide (the owner of the repository) these days.

As with everything, it's not set in stone, so we can evaluate at a later date another tool that suits us better (even `devenv`, I'm not excluding it by any means). I'm always open to exploring new ideas.

**Comment by brianmcgee** [comment]
@aldoborrero can you sign the commits?

**Comment by aldoborrero** [comment]
Mmm, it seems `hercules-ci` is behaving weirdly today...

**Review by selfuryon — APPROVED** [review]
LGTM

**Pull request merged**
