### PR TITLE
lighthouse: 4.6.0 -> 5.0.0

### PR DESCRIPTION
**Pull request by selfuryon**
Diff: https://github.com/sigp/lighthouse/compare/v4.6.0...v5.0.0

### CODE REVIEW

**Review by brianmcgee — APPROVED** [review]
Lgtm

**Comment by selfuryon** [comment]
hm, build error, need to investigate why

**Comment by jhvst** [comment]
One of the things to also take into account is that the Rust version has to be from unstable now: https://github.com/sigp/lighthouse/commit/a264afd19ff1d8d4a9ce1e673386722ccb0e31ec#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557R1

**Comment by zimbatm** [comment]
Because of the ./use-c-kzg-from-crates-io.patch patch, you must re-generate the Cargo.lock.

**Comment by actias-nebula** [comment]
bump, it would be nice to have this in before Dencun

**Review by brianmcgee — APPROVED** [review]
lgtm

**Pull request merged**
