### PR TITLE
lighthouse: 4.5.0 -> 4.6.0

### PR DESCRIPTION
**Pull request by zimbatm**

### CODE REVIEW

**Comment by zimbatm** [comment]
Currently failing with:
```
       >   HOST_CC = Some("/nix/store/sfgnb6rr428bssyrs54d6d0vv2avi95c-gcc-wrapper-12.3.0/bin/cc")
       >   cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
       >   CRATE_CC_NO_DEFAULTS = None
       >   DEBUG = Some("false")
       >   CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
       >   cargo:rerun-if-env-changed=CFLAGS_x86_64-unknown-linux-gnu
       >   CFLAGS_x86_64-unknown-linux-gnu = None
       >   cargo:rerun-if-env-changed=CFLAGS_x86_64_unknown_linux_gnu
       >   CFLAGS_x86_64_unknown_linux_gnu = None
       >   cargo:rerun-if-env-changed=HOST_CFLAGS
       >   HOST_CFLAGS = None
       >   cargo:rerun-if-env-changed=CFLAGS
       >   CFLAGS = None
       >   running: "/nix/store/sfgnb6rr428bssyrs54d6d0vv2avi95c-gcc-wrapper-12.3.0/bin/cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "/build/blst/bindings" "-o" "/build/source/target/release/build/c-kzg-23350a5e7b5087f3/out/901ff3bb8e9e7f78-c_kzg_4844.o" "-c" "/build/src/c_kzg_4844.c"
       >   cargo:warning=cc1: fatal error: /build/src/c_kzg_4844.c: No such file or directory
       >
       >   cargo:warning=compilation terminated.
       >
       >   exit status: 1
       >
       >   --- stderr
       >   thread 'main' panicked at /build/cargo-vendor-dir/c-kzg-0.1.0/build.rs:35:28:
       >   Failed to compile ckzg: Error { kind: ToolExecError, message: "Command \"/nix/store/sfgnb6rr428bssyrs54d6d0vv2avi95c-gcc-wrapper-12.3.0/bin/cc\" \"-O0\" \"-ffunction-sections\" \"-fdata-sections\" \"-fPIC\" \"-m64\" \"-I\" \"/build/blst/bindings\" \"-o\" \"/build/source/target/release/build/c-kzg-23350a5e7b5087f3/out/901ff3bb8e9e7f78-c_kzg_4844.o\" \"-c\" \"/build/src/c_kzg_4844.c\" with args \"cc\" did not execute successfully (status code exit status: 1)." }
       >   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
       > warning: build failed, waiting for other jobs to finish...
```

**Comment by tthebst** [comment]
Lighthouse 4.6  is needed to run after the testnet upgrades.

**Comment by tthebst** [comment]
There is this [MR](https://github.com/NixOS/nixpkgs/pull/284864/files) to bump lighthouse in Nixpkgs. It patches the kzg dependency

**Comment by zimbatm** [comment]
thanks, after copying a bunch of things from upstream, it's working as expected.

**Comment by tthebst** [comment]
It would be nice to merge this. My testnet validator is ded.

**Comment by aldoborrero** [comment]
@zimbatm is still in draft?

**Review by aldoborrero — APPROVED** [review]

**Pull request merged**
