### PR TITLE
feat(reth): add reth execution client

### LINKED ISSUE #323: Add support for reth
Today was the first `reth` alpha release, we need to add that. The main problem is they use rust `1.70.0` which isn't released yet in nixpkgs, so I'm awaiting the needed rust release will be available in nixpkgs.

### PR DESCRIPTION
**Pull request by selfuryon**
Add `reth` EL client.

Close #323

### CODE REVIEW

**Comment by selfuryon** [comment]
Related to https://github.com/boa-dev/boa/pull/3074

**Comment by selfuryon** [comment]
Asked in `reth` [telegram chat](https://t.me/paradigm_reth/9501) about boa dependency

**Comment by georgewhewell** [comment]
@selfuryon thanks for this. since https://github.com/paradigmxyz/reth/pull/3820 `boa` was updated, [i changed this pr to use main branch](https://github.com/nix-community/ethereum.nix/compare/feat/reth...georgewhewell:ethereum.nix:feat/reth) and it builds correctly now. i guess next release should work

**Comment by selfuryon** [comment]
@georgewhewell Thanks for information! I'll wait that!

**Comment by dzmitry-lahoda** [comment]
so can this be merged?

**Comment by selfuryon** [comment]
> so can this be merged?

Previously I had troubles with bindgen, cuz they have two dependencies with the same version of bindgen, but with two different links to it (git and cargo), and `cargo vendor` couldn't vendor them. But now I see that the error is different. I'll try to fix that

**Comment by dzmitry-lahoda** [comment]
>  (git and cargo)

oh, never solved such issue before. give cargo good with it - may be raise/search issue on nixpkgs?

also consider asking https://github.com/ipetkov/crane/ here. it clever wrapper around nixpkgs. it may fixed or or at least author more agile to fix

**Comment by selfuryon** [comment]
Looks like the same situation, but with `c-kzg` now...
```console
$ cat Cargo.lock | rg "c-kzg"
name = "c-kzg"
source = "git+https://github.com/ethereum/c-kzg-4844?rev=f5f6f863d475847876a2bd5ee252058d37c3a15d#f5f6f863d475847876a2bd5ee252058d37c3a15d"
name = "c-kzg"
source = "git+https://github.com/ethereum/c-kzg-4844#fbef59a3f9e8fa998bdb5069d212daf83d586aa5"
```

**Comment by dzmitry-lahoda** [comment]
just direct call to cargo vendor without nix works? vendor has bugs too btw (so can race 4th issue onto rust)

read error, do not see root cause/workaround yet - only nix patch as solution, which is ugly

**Comment by dzmitry-lahoda** [comment]
so error, like it vendored and nix stored lib. than tried to repeat under different subfolder as naming different. sure previous store read only. 

feels like pure nix bug of nixpkgs. i guess bug exists on nixpkgs already of good to find/create.  

if that is the case, big sed patch is way to go + bug on nixpkgs for tracking.

**Comment by selfuryon** [comment]
Asked about that case in [reth chat](https://t.me/paradigm_reth/15363)

**Comment by dzmitry-lahoda** [comment]
Actually it may be bug in cargo too.

**Comment by selfuryon** [comment]
Open an issue in reth: https://github.com/paradigmxyz/reth/issues/4826

Cargo also has opened issue about that situation: https://github.com/rust-lang/cargo/issues/10310 without any resolution for now... So it's inconsistent behavior between `cargo build` and `cargo vendor`

**Comment by selfuryon** [comment]
Finally, I can build reth with nix. But I confused by `buildbot` cuz it has only 13 checks and I can't find reth there. Is it ok?

**Comment by aldoborrero** [comment]
@selfuryon it should build all apps as we're using `devour-flake`

Also, would you mind adding `reth` to the list of `docs/apps.md` :)

**Comment by selfuryon** [comment]
> @selfuryon it should build all apps as we're using `devour-flake`
> 
> Also, would you mind adding `reth` to the list of `docs/apps.md` :)

Thanks, I added reth to `apps.md`. I also tested the CI: I commented the problem test in build manifest, locally I can't build this package due to failed test, but I see that CI shows everything is fine.

@aldoborrero Can you pls check that you also can't build that package locally. If so, something works not like we want.

**Comment by aldoborrero** [comment]
When running locally I'm obtaining:

```
framework :: Dev/nix-community/ethereum.nix ‹feat/reth› % g pull                                                                                                                                                                                                                                                                                                          
remote: Enumerating objects: 11, done.
remote: Counting objects: 100% (11/11), done.
remote: Compressing objects: 100% (1/1), done.
remote: Total 6 (delta 3), reused 6 (delta 3), pack-reused 0
Unpacking objects: 100% (6/6), 506 bytes | 29.00 KiB/s, done.
From github.com:nix-community/ethereum.nix
   5e297e5..8a43a3d  gh-pages   -> origin/gh-pages
Updating cb62d19..14b6745
Fast-forward
 docs/apps.md                                |  1 +
 packages/clients/execution/reth/default.nix | 46 ++++++++++++++++++++++++++++++++++++++++++++++
 packages/default.nix                        |  2 ++
 3 files changed, 49 insertions(+)
 create mode 100644 packages/clients/execution/reth/default.nix
framework :: Dev/nix-community/ethereum.nix ‹feat/reth› % nix build .#reth                                                                                                                                                                                                                                                                                                
error: builder for '/nix/store/qbqjshqhbfsswbadd95a7bryazprlmcy-reth-0.1.0-alpha.11.drv' failed with exit code 101;
       last 30 log lines:
       > test node::tests::parse_metrics_port ... ok
       > test node::tests::parse_config_path ... ok
       > test node::tests::parse_db_path ... ok
       > test node::tests::parse_dev ... ok
       > test version::tests::assert_extradata_less_32bytes ... ok
       > test node::tests::parse_common_node_command_chain_args ... ok
       > test node::tests::parse_instance ... ok
       > test node::tests::parse_port ... ok
       > test cli::tests::parse_color_mode ... ok
       > test cli::tests::override_trusted_setup_file ... FAILED
       > test cli::tests::parse_logs_path ... ok
       > test init::tests::success_init_genesis_sepolia ... ok
       > test init::tests::fail_init_inconsistent_db ... ok
       > test init::tests::success_init_genesis_goerli ... ok
       > test init::tests::init_genesis_history ... ok
       > test init::tests::success_init_genesis_mainnet ... ok
       >
       > failures:
       >
       > ---- cli::tests::override_trusted_setup_file stdout ----
       > thread 'cli::tests::override_trusted_setup_file' panicked at 'Could not create log directory: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', /build/source/crates/tracing/src/lib.rs:86:42
       > note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
       >
       >
       > failures:
       >     cli::tests::override_trusted_setup_file
       >
       > test result: FAILED. 56 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.06s
       >
       > error: test failed, to rerun pass `--lib`
       For full logs, run 'nix log /nix/store/qbqjshqhbfsswbadd95a7bryazprlmcy-reth-0.1.0-alpha.11.drv'.
framework :: Dev/nix-community/ethereum.nix ‹feat/reth› %
```

I'll double-check why is not building all inputs on CI with Mic92 tomorrow (maybe I need to re-add nix flake check that uses devour-flake under the hood)

**Comment by selfuryon** [comment]
> @selfuryon when running locally I'm obtaining:
> 
> ```
> framework :: Dev/nix-community/ethereum.nix ‹feat/reth› % g pull                                                                                                                                                                                                                                                                                                          
> remote: Enumerating objects: 11, done.
> remote: Counting objects: 100% (11/11), done.
> remote: Compressing objects: 100% (1/1), done.
> remote: Total 6 (delta 3), reused 6 (delta 3), pack-reused 0
> Unpacking objects: 100% (6/6), 506 bytes | 29.00 KiB/s, done.
> From github.com:nix-community/ethereum.nix
>    5e297e5..8a43a3d  gh-pages   -> origin/gh-pages
> Updating cb62d19..14b6745
> Fast-forward
>  docs/apps.md                                |  1 +
>  packages/clients/execution/reth/default.nix | 46 ++++++++++++++++++++++++++++++++++++++++++++++
>  packages/default.nix                        |  2 ++
>  3 files changed, 49 insertions(+)
>  create mode 100644 packages/clients/execution/reth/default.nix
> framework :: Dev/nix-community/ethereum.nix ‹feat/reth› % nix build .#reth                                                                                                                                                                                                                                                                                                
> error: builder for '/nix/store/qbqjshqhbfsswbadd95a7bryazprlmcy-reth-0.1.0-alpha.11.drv' failed with exit code 101;
>        last 30 log lines:
>        > test node::tests::parse_metrics_port ... ok
>        > test node::tests::parse_config_path ... ok
>        > test node::tests::parse_db_path ... ok
>        > test node::tests::parse_dev ... ok
>        > test version::tests::assert_extradata_less_32bytes ... ok
>        > test node::tests::parse_common_node_command_chain_args ... ok
>        > test node::tests::parse_instance ... ok
>        > test node::tests::parse_port ... ok
>        > test cli::tests::parse_color_mode ... ok
>        > test cli::tests::override_trusted_setup_file ... FAILED
>        > test cli::tests::parse_logs_path ... ok
>        > test init::tests::success_init_genesis_sepolia ... ok
>        > test init::tests::fail_init_inconsistent_db ... ok
>        > test init::tests::success_init_genesis_goerli ... ok
>        > test init::tests::init_genesis_history ... ok
>        > test init::tests::success_init_genesis_mainnet ... ok
>        >
>        > failures:
>        >
>        > ---- cli::tests::override_trusted_setup_file stdout ----
>        > thread 'cli::tests::override_trusted_setup_file' panicked at 'Could not create log directory: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', /build/source/crates/tracing/src/lib.rs:86:42
>        > note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
>        >
>        >
>        > failures:
>        >     cli::tests::override_trusted_setup_file
>        >
>        > test result: FAILED. 56 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.06s
>        >
>        > error: test failed, to rerun pass `--lib`
>        For full logs, run 'nix log /nix/store/qbqjshqhbfsswbadd95a7bryazprlmcy-reth-0.1.0-alpha.11.drv'.
> framework :: Dev/nix-community/ethereum.nix ‹feat/reth› %
> ```
> 
> I'll double-check why is not building all inputs on CI with Mic92 tomorrow (maybe I need to re-add nix flake check that uses devour-flake under the hood)

Now it works fine, I checked with failed tests, and CI can't build it, so it works :)

**Comment by selfuryon** [comment]
@aldoborrero @brianmcgee Can you check this PR pls?

**Pull request merged**
