### PR TITLE
feat: Implement lighthouse beacon service

### LINKED ISSUE #20: Add a service for lighthouse
We would like to configure the lighthouse client within nixos easily.

### PR DESCRIPTION
**Pull request by scottbot95**
Implement services for Lighthouse Beacon Node and Validator Client.

I feel like the only particularly controversial thing in this PR is making the network default to the name of the beacon/validator service.

Resolves #20

### CODE REVIEW

**Comment by aldoborrero** [comment]
@scottbot95 nice work! Thanks again for taking the time to contribute! 

As one extra request, do you think can you add some light tests to check the module works properly (like for example we have done for [prysm](https://github.com/nix-community/ethereum.nix/blob/main/modules/prysm-validator/default.test.nix))?

**Comment by scottbot95** [comment]
I am going on vacation soon so I might not get to it for a week or two, but I could certainly look into some tests

**Comment by aldoborrero** [comment]
@scottbot95 OK, we can merge this PR and add tests after

**Review by aldoborrero — APPROVED** [review]

**Comment by scottbot95** [comment]
I'm in no rush to merge this personally. Do whatever you feel is best for the project.

**Comment by aldoborrero** [comment]
This PR as it is provides value ;) (if there's any bug we can sort it out later)

**Comment by aldoborrero** [comment]
@scottbot95 yeah, you're right about the `ExecStart`. I experienced it a couple of months ago with one client by not being aware of it. 

When I was working on the problem, instead, I decided to implement multiple strategies to check the service was starting correctly, but also double-checking that the ports were open and checking if the logs contained anything related to an error message. 

Below you can see a completely invented example of what I'm describing. We can take that approach and improve the testing based on that. As the code of the tests is pure Python we can do more clever checks.

What do you think?

```nix
testScript = {nodes, ...}: ''
      def wait_for_units(node, units):
        for unit in units:
          node.wait_for_unit(unit)

      def check_ports(node, ports):
        for port in ports:
          node.wait_for_open_port(port)

      start_all()

      # Service Status
      wait_for_units(portal, [ "bitcoind.service", "geth.service"])
      client.wait_for_unit("multi-user.target")

      # Port Accessibility
      check_ports(portal, [9001, 9002, 18500])

      # Data Persistence
      portal.succeed("test -f /var/lib/geth/chain/wallet.db")

      # Error Logs
      portal.fail("journalctl -u geth.service | grep -i 'error'")
    '';
```

**Comment by scottbot95** [comment]
This approach seems pretty good. Checking ports/logs/files is probably the only things we can realistically check for. We could probably also come up with a message to expect from in logs. In the case of the Lighthouse Validator, we could probably search for `INFO Connected to beacon node(s)`

**Pull request merged**
