### PR TITLE
nethermind: 1.19.3 -> 1.25.3

### PR DESCRIPTION
**Pull request by selfuryon**
I tried to upgrade nethermind, but I stuck with a problem with [PackageSourceMapping](https://github.com/NethermindEth/nethermind/commit/929833530bb1b48d68d7f49c33475529677fbf3d) in a new release.

PackageSourceMapping was enabled to use two sources for nuget packages:
* `nuget.org` as a default option
* `nugettest.org` for `Nethermind.DotNetty` packages

Problems:
* `nix run .#nethermind.fetch-nethermind-deps packages/clients/execution/nethermind/nuget-deps.nix` works, but produce an empty hash for packages from `nugettest.org`. Looks like an embedded script doesn't work with `nuget.config`
* if `PackageSourceMapping` is enabled, I can't restore packages in `buildDotnetModule` build phase anymore with my own source: internal `env dotnet restore src/Nethermind/Nethermind.sln ... --source <nix-store>/nuget-source/lib` ignores source option `PackageSourceMapping is enabled, the following source(s) were not considered <nix-store>/nuget-source/lib`
* if I disable `PackageSourceMapping`, dotnet can't find any `nugettest.org` related packages...

I didn't find an option for a cache directory with `PackageSourceMapping` configuration, but maybe I just missed it (I've never worked before with dotnet). Trying to fix...

### CODE REVIEW

**Comment by aldoborrero** [comment]
@selfuryon I'll have a look

**Comment by aldoborrero** [comment]
`fetch-deps` by default the `url` parameter points to `nuget.org`. We can overcome that by just overriding it:

```nix
  (fetchNuGet { pname = "Nethermind.Crypto.SecP256k1"; version = "1.0.1"; sha256 = "0vmkv5zmr15lakcbi4ilicrk671igfw2n4nk1b6bbxdhy7vga3yw"; })
  (fetchNuGet rec { pname = "Nethermind.DotNetty.Buffers"; version = "1.0.1-preview.2"; sha256 = "sha256-S1LLt2GPojb3WVphgLXAT51/knOa1K4RCAZD8zt1o1k=";  url = "https://int.nugettest.org/api/v2/package/${pname}/${version}"; })
  (fetchNuGet rec { pname = "Nethermind.DotNetty.Codecs"; version = "1.0.1-preview.2"; sha256 = "sha256-djPtw0REDNcjL+uFQZ5BwFf63GsETOsTUL9HmZvm3Pw="; url = "https://int.nugettest.org/api/v2/package/${pname}/${version}"; })
  (fetchNuGet rec { pname = "Nethermind.DotNetty.Common"; version = "1.0.1-preview.2"; sha256 = "sha256-sb9uN5KDpw5BAfORVF8aB8xAkjnuA4xd14yinFDk3YU="; url = "https://int.nugettest.org/api/v2/package/${pname}/${version}"; })
  (fetchNuGet rec { pname = "Nethermind.DotNetty.Handlers"; version = "1.0.1-preview.2"; sha256 = "sha256-bjMRcH6azDfYTJXaxAfaS2cfGrVZuYYMd+LX5xGBBiY="; url = "https://int.nugettest.org/api/v2/package/${pname}/${version}"; })
  (fetchNuGet rec { pname = "Nethermind.DotNetty.Transport"; version = "1.0.1-preview.2"; sha256 = "sha256-MHfjnBHcrFiBpNSI+K265NTot/GLsPPGRfzwdDh4bjc="; url = "https://int.nugettest.org/api/v2/package/${pname}/${version}"; })
```
But after doing that, I'm seeing the same errors you were reporting with `PackageSourceMapping`. I'm investigating the root cause...

**Comment by aldoborrero** [comment]
With the latest changes I obtain the following traces:

```
  Nethermind.Consensus.Ethash -> /nix/store/zjkrxvzzw3az0y4l395p8j9a9pfnry4k-nethermind-1.21.0/lib/nethermind/
  Nethermind.Network.Discovery -> /nix/store/zjkrxvzzw3az0y4l395p8j9a9pfnry4k-nethermind-1.21.0/lib/nethermind/
  Nethermind.Hive -> /nix/store/zjkrxvzzw3az0y4l395p8j9a9pfnry4k-nethermind-1.21.0/lib/nethermind/
  Nethermind.Network.Enr -> /nix/store/zjkrxvzzw3az0y4l395p8j9a9pfnry4k-nethermind-1.21.0/lib/nethermind/
  Nethermind.Network -> /nix/store/zjkrxvzzw3az0y4l395p8j9a9pfnry4k-nethermind-1.21.0/lib/nethermind/
  Nethermind.Init -> /nix/store/zjkrxvzzw3az0y4l395p8j9a9pfnry4k-nethermind-1.21.0/lib/nethermind/
  Nethermind.AccountAbstraction -> /nix/store/zjkrxvzzw3az0y4l395p8j9a9pfnry4k-nethermind-1.21.0/lib/nethermind/
  Nethermind.Consensus.AuRa -> /nix/store/zjkrxvzzw3az0y4l395p8j9a9pfnry4k-nethermind-1.21.0/lib/nethermind/
  Nethermind.JsonRpc.TraceStore.Test -> /nix/store/zjkrxvzzw3az0y4l395p8j9a9pfnry4k-nethermind-1.21.0/lib/nethermind/
/build/tmp.VOjlax5fnd/.nuget/packages/microsoft.codecoverage/17.6.3/build/netstandard2.0/Microsoft.CodeCoverage.targets(23,5): warning MSB3026: Could not copy "/build/tmp.VOjlax5fnd/.nuget/packages/microsoft.codecoverage/17.6.3/build/netstandard2.0/CodeCoverage/amd64/CodeCoverage.exe" to "/nix/store/zjkrxvzzw3az0y4l395p8j9a9pfnry4k-nethermind-1.21.0/lib/nethermind/CodeCoverage/amd64/CodeCoverage.exe". Beginning retry 1 in 1000ms. The process cannot access the file '/nix/store/zjkrxvzzw3az0y4l395p8j9a9pfnry4k-nethermind-1.21.0/lib/nethermind/CodeCoverage/amd64/CodeCoverage.exe' because it is being used by another process.  [/build/source/src/Nethermind/Nethermind.Config.Test/Nethermind.Config.Test.csproj]
/build/tmp.VOjlax5fnd/.nuget/packages/microsoft.codecoverage/17.6.3/build/netstandard2.0/Microsoft.CodeCoverage.targets(23,5): warning MSB3026: Could not copy "/build/tmp.VOjlax5fnd/.nuget/packages/microsoft.codecoverage/17.6.3/build/netstandard2.0/CodeCoverage/amd64/covrun64.dll" to "/nix/store/zjkrxvzzw3az0y4l395p8j9a9pfnry4k-nethermind-1.21.0/lib/nethermind/CodeCoverage/amd64/covrun64.dll". Beginning retry 1 in 1000ms. The process cannot access the file '/nix/store/zjkrxvzzw3az0y4l395p8j9a9pfnry4k-nethermind-1.21.0/lib/nethermind/CodeCoverage/amd64/covrun64.dll' because it is being used by another process.  [/build/source/src/Nethermind/Nethermind.Config.Test/Nethermind.Config.Test.csproj]
/build/tmp.VOjlax5fnd/.nuget/packages/microsoft.codecoverage/17.6.3/build/netstandard2.0/Microsoft.CodeCoverage.targets(23,5): warning MSB3026: Could not copy "/build/tmp.VOjlax5fnd/.nuget/packages/microsoft.codecoverage/17.6.3/build/netstandard2.0/CodeCoverage/amd64/msdia140.dll" to "/nix/store/zjkrxvzzw3az0y4l395p8j9a9pfnry4k-nethermind-1.21.0/lib/nethermind/CodeCoverage/amd64/msdia140.dll". Beginning retry 1 in 1000ms. The process cannot access the file '/nix/store/zjkrxvzzw3az0y4l395p8j9a9pfnry4k-nethermind-1.21.0/lib/nethermind/CodeCoverage/amd64/msdia140.dll' because it is being used by another process.  [/build/source/src/Nethermind/Nethermind.State.Test/Nethermind.State.Test.csproj]
/build/tmp.VOjlax5fnd/.nuget/packages/microsoft.codecoverage/17.6.3/build/netstandard2.0/Microsoft.CodeCoverage.targets(23,5): warning MSB3026: Could not copy "/build/tmp.VOjlax5fnd/.nuget/packages/microsoft.codecoverage/17.6.3/build/netstandard2.0/InstrumentationEngine/alpine/x64/libInstrumentationEngine.so" to "/nix/store/zjkrxvzzw3az0y4l395p8j9a9pfnry4k-nethermind-1.21.0/lib/nethermind/InstrumentationEngine/alpine/x64/libInstrumentationEngine.so". Beginning retry 1 in 1000ms. The process cannot access the file '/nix/store/zjkrxvzzw3az0y4l395p8j9a9pfnry4k-nethermind-1.21.0/lib/nethermind/InstrumentationEngine/alpine/x64/libInstrumentationEngine.so' because it is being used by another process.  [/build/source/src/Nethermind/Nethermind.Network.Test/Nethermind.Network.Test.csproj]
  Nethermind.Overseer.Test -> /nix/store/zjkrxvzzw3az0y4l395p8j9a9pfnry4k-nethermind-1.21.0/lib/nethermind/
  Nethermind.Synchronization -> /nix/store/zjkrxvzzw3az0y4l395p8j9a9pfnry4k-nethermind-1.21.0/lib/nethermind/
  Nethermind.Network.Enr.Test -> /nix/store/zjkrxvzzw3az0y4l395p8j9a9pfnry4k-nethermind-1.21.0/lib/nethermind/
  Nethermind.Db.Rocks -> /nix/store/zjkrxvzzw3az0y4l395p8j9a9pfnry4k-nethermind-1.21.0/lib/nethermind/
  Nethermind.Network.Dns.Test -> /nix/store/zjkrxvzzw3az0y4l395p8j9a9pfnry4k-nethermind-1.21.0/lib/nethermind/
  Nethermind.Mining.Test -> /nix/store/zjkrxvzzw3az0y4l395p8j9a9pfnry4k-nethermind-1.21.0/lib/nethermind/
  Nethermind.TxPool.Test -> /nix/store/zjkrxvzzw3az0y4l395p8j9a9pfnry4k-nethermind-1.21.0/lib/nethermind/
  Nethermind.Sockets.Test -> /nix/store/zjkrxvzzw3az0y4l395p8j9a9pfnry4k-nethermind-1.21.0/lib/nethermind/
  Nethermind.Tools.GasHistorian -> /nix/store/zjkrxvzzw3az0y4l395p8j9a9pfnry4k-nethermind-1.21.0/lib/nethermind/
  Nethermind.KeyStore.Test -> /nix/store/zjkrxvzzw3az0y4l395p8j9a9pfnry4k-nethermind-1.21.0/lib/nethermind/
  Nethermind.JsonRpc.TraceStore -> /nix/store/zjkrxvzzw3az0y4l395p8j9a9pfnry4k-nethermind-1.21.0/lib/nethermind/
  Nethermind.JsonRpc -> /nix/store/zjkrxvzzw3az0y4l395p8j9a9pfnry4k-nethermind-1.21.0/lib/nethermind/
  Nethermind.Mev -> /nix/store/zjkrxvzzw3az0y4l395p8j9a9pfnry4k-nethermind-1.21.0/lib/nethermind/
  Nethermind.Network.Dns -> /nix/store/zjkrxvzzw3az0y4l395p8j9a9pfnry4k-nethermind-1.21.0/lib/nethermind/
  Nethermind.Api -> /nix/store/zjkrxvzzw3az0y4l395p8j9a9pfnry4k-nethermind-1.21.0/lib/nethermind/
  Nethermind.Db.Rpc -> /nix/store/zjkrxvzzw3az0y4l395p8j9a9pfnry4k-nethermind-1.21.0/lib/nethermind/
  Nethermind.Consensus.Clique -> /nix/store/zjkrxvzzw3az0y4l395p8j9a9pfnry4k-nethermind-1.21.0/lib/nethermind/
  Nethermind.Cli -> /nix/store/zjkrxvzzw3az0y4l395p8j9a9pfnry4k-nethermind-1.21.0/lib/nethermind/
  Nethermind.Facade -> /nix/store/zjkrxvzzw3az0y4l395p8j9a9pfnry4k-nethermind-1.21.0/lib/nethermind/
  Nethermind.Trie.Test -> /nix/store/zjkrxvzzw3az0y4l395p8j9a9pfnry4k-nethermind-1.21.0/lib/nethermind/
  Nethermind.Merge.AuRa -> /nix/store/zjkrxvzzw3az0y4l395p8j9a9pfnry4k-nethermind-1.21.0/lib/nethermind/
  Nethermind.HealthChecks -> /nix/store/zjkrxvzzw3az0y4l395p8j9a9pfnry4k-nethermind-1.21.0/lib/nethermind/
/build/tmp.VOjlax5fnd/.nuget/packages/microsoft.codecoverage/17.6.3/build/netstandard2.0/Microsoft.CodeCoverage.targets(23,5): warning MSB3026: Could not copy "/build/tmp.VOjlax5fnd/.nuget/packages/microsoft.codecoverage/17.6.3/build/netstandard2.0/CodeCoverage/CodeCoverage.exe" to "/nix/store/zjkrxvzzw3az0y4l395p8j9a9pfnry4k-nethermind-1.21.0/lib/nethermind/CodeCoverage/CodeCoverage.exe". Beginning retry 1 in 1000ms. The process cannot access the file '/nix/store/zjkrxvzzw3az0y4l395p8j9a9pfnry4k-nethermind-1.21.0/lib/nethermind/CodeCoverage/CodeCoverage.exe' because it is being used by another process.  [/build/source/src/Nethermind/Nethermind.State.Test/Nethermind.State.Test.csproj]
/build/tmp.VOjlax5fnd/.nuget/packages/microsoft.codecoverage/17.6.3/build/netstandard2.0/Microsoft.CodeCoverage.targets(23,5): warning MSB3026: Could not copy "/build/tmp.VOjlax5fnd/.nuget/packages/microsoft.codecoverage/17.6.3/build/netstandard2.0/CodeCoverage/CodeCoverage.config" to "/nix/store/zjkrxvzzw3az0y4l395p8j9a9pfnry4k-nethermind-1.21.0/lib/nethermind/CodeCoverage/CodeCoverage.config". Beginning retry 1 in 1000ms. The process cannot access the file '/nix/store/zjkrxvzzw3az0y4l395p8j9a9pfnry4k-nethermind-1.21.0/lib/nethermind/CodeCoverage/CodeCoverage.config' because it is being used by another process.  [/build/source/src/Nethermind/Nethermind.State.Test/Nethermind.State.Test.csproj]
/build/tmp.VOjlax5fnd/.nuget/packages/microsoft.codecoverage/17.6.3/build/netstandard2.0/Microsoft.CodeCoverage.targets(23,5): warning MSB3026: Could not copy "/build/tmp.VOjlax5fnd/.nuget/packages/microsoft.codecoverage/17.6.3/build/netstandard2.0/CodeCoverage/covrun32.dll" to "/nix/store/zjkrxvzzw3az0y4l395p8j9a9pfnry4k-nethermind-1.21.0/lib/nethermind/CodeCoverage/covrun32.dll". Beginning retry 1 in 1000ms. The process cannot access the file '/nix/store/zjkrxvzzw3az0y4l395p8j9a9pfnry4k-nethermind-1.21.0/lib/nethermind/CodeCoverage/covrun32.dll' because it is being used by another process.  [/build/source/src/Nethermind/Nethermind.State.Test/Nethermind.State.Test.csproj]
/build/tmp.VOjlax5fnd/.nuget/packages/microsoft.codecoverage/17.6.3/build/netstandard2.0/Microsoft.CodeCoverage.targets(23,5): warning MSB3026: Could not copy "/build/tmp.VOjlax5fnd/.nuget/packages/microsoft.codecoverage/17.6.3/build/netstandard2.0/CodeCoverage/msdia140.dll" to "/nix/store/zjkrxvzzw3az0y4l395p8j9a9pfnry4k-nethermind-1.21.0/lib/nethermind/CodeCoverage/msdia140.dll". Beginning retry 1 in 1000ms. The process cannot access the file '/nix/store/zjkrxvzzw3az0y4l395p8j9a9pfnry4k-nethermind-1.21.0/lib/nethermind/CodeCoverage/msdia140.dll' because it is being used by another process.  [/build/source/src/Nethermind/Nethermind.State.Test/Nethermind.State.Test.csproj]
/build/tmp.VOjlax5fnd/.nuget/packages/microsoft.codecoverage/17.6.3/build/netstandard2.0/Microsoft.CodeCoverage.targets(23,5): warning MSB3026: Could not copy "/build/tmp.VOjlax5fnd/.nuget/packages/microsoft.codecoverage/17.6.3/build/netstandard2.0/CodeCoverage/amd64/CodeCoverage.exe" to "/nix/store/zjkrxvzzw3az0y4l395p8j9a9pfnry4k-nethermind-1.21.0/lib/nethermind/CodeCoverage/amd64/CodeCoverage.exe". Beginning retry 1 in 1000ms. The process cannot access the file '/nix/store/zjkrxvzzw3az0y4l395p8j9a9pfnry4k-nethermind-1.21.0/lib/nethermind/CodeCoverage/amd64/CodeCoverage.exe' because it is being used by another process.  [/build/source/src/Nethermind/Nethermind.Core.Test/Nethermind.Core.Test.csproj]
/build/tmp.VOjlax5fnd/.nuget/packages/microsoft.codecoverage/17.6.3/build/netstandard2.0/Microsoft.CodeCoverage.targets(23,5): warning MSB3026: Could not copy "/build/tmp.VOjlax5fnd/.nuget/packages/microsoft.codecoverage/17.6.3/build/netstandard2.0/CodeCoverage/amd64/covrun64.dll" to "/nix/store/zjkrxvzzw3az0y4l395p8j9a9pfnry4k-nethermind-1.21.0/lib/nethermind/CodeCoverage/amd64/covrun64.dll". Beginning retry 1 in 1000ms. The process cannot access the file '/nix/store/zjkrxvzzw3az0y4l395p8j9a9pfnry4k-nethermind-1.21.0/lib/nethermind/CodeCoverage/amd64/covrun64.dll' because it is being used by another process.  [/build/source/src/Nethermind/Nethermind.Core.Test/Nethermind.Core.Test.csproj]
/build/tmp.VOjlax5fnd/.nuget/packages/microsoft.codecoverage/17.6.3/build/netstandard2.0/Microsoft.CodeCoverage.targets(23,5): warning MSB3026: Could not copy "/build/tmp.VOjlax5fnd/.nuget/packages/microsoft.codecoverage/17.6.3/build/netstandard2.0/CodeCoverage/amd64/VanguardInstrumentationProfiler_x64.config" to "/nix/store/zjkrxvzzw3az0y4l395p8j9a9pfnry4k-nethermind-1.21.0/lib/nethermind/CodeCoverage/amd64/VanguardInstrumentationProfiler_x64.config". Beginning retry 1 in 1000ms. The process cannot access the file '/nix/store/zjkrxvzzw3az0y4l395p8j9a9pfnry4k-nethermind-1.21.0/lib/nethermind/CodeCoverage/amd64/VanguardInstrumentationProfiler_x64.config' because it is being used by another process.  [/build/source/src/Nethermind/Nethermind.Core.Test/Nethermind.Core.Test.csproj]
/build/tmp.VOjlax5fnd/.nuget/packages/microsoft.codecoverage/17.6.3/build/netstandard2.0/Microsoft.CodeCoverage.targets(23,5): warning MSB3026: Could not copy "/build/tmp.VOjlax5fnd/.nuget/packages/microsoft.codecoverage/17.6.3/build/netstandard2.0/CodeCoverage/amd64/msdia140.dll" to "/nix/store/zjkrxvzzw3az0y4l395p8j9a9pfnry4k-nethermind-1.21.0/lib/nethermind/CodeCoverage/amd64/msdia140.dll". Beginning retry 1 in 1000ms. The process cannot access the file '/nix/store/zjkrxvzzw3az0y4l395p8j9a9pfnry4k-nethermind-1.21.0/lib/nethermind/CodeCoverage/amd64/msdia140.dll' because it is being used by another process.  [/build/source/src/Nethermind/Nethermind.Core.Test/Nethermind.Core.Test.csproj]
/build/tmp.VOjlax5fnd/.nuget/packages/microsoft.codecoverage/17.6.3/build/netstandard2.0/Microsoft.CodeCoverage.targets(23,5): warning MSB3026: Could not copy "/build/tmp.VOjlax5fnd/.nuget/packages/microsoft.codecoverage/17.6.3/build/netstandard2.0/CodeCoverage/amd64/CodeCoverage.exe" to "/nix/store/zjkrxvzzw3az0y4l395p8j9a9pfnry4k-nethermind-1.21.0/lib/nethermind/CodeCoverage/amd64/CodeCoverage.exe". Beginning retry 1 in 1000ms. The process cannot access the file '/nix/store/zjkrxvzzw3az0y4l395p8j9a9pfnry4k-nethermind-1.21.0/lib/nethermind/CodeCoverage/amd64/CodeCoverage.exe' because it is being used by another process.  [/build/source/src/Nethermind/Nethermind.Ethash.Test/Nethermind.Ethash.Test.csproj]
/build/tmp.VOjlax5fnd/.nuget/packages/microsoft.codecoverage/17.6.3/build/netstandard2.0/Microsoft.CodeCoverage.targets(23,5): warning MSB3026: Could not copy "/build/tmp.VOjlax5fnd/.nuget/packages/microsoft.codecoverage/17.6.3/build/netstandard2.0/CodeCoverage/amd64/covrun64.dll" to "/nix/store/zjkrxvzzw3az0y4l395p8j9a9pfnry4k-nethermind-1.21.0/lib/nethermind/CodeCoverage/amd64/covrun64.dll". Beginning retry 1 in 1000ms. The process cannot access the file '/nix/store/zjkrxvzzw3az0y4l395p8j9a9pfnry4k-nethermind-1.21.0/lib/nethermind/CodeCoverage/amd64/covrun64.dll' because it is being used by another process.  [/build/source/src/Nethermind/Nethermind.Ethash.Test/Nethermind.Ethash.Test.csproj]
/build/tmp.VOjlax5fnd/.nuget/packages/microsoft.codecoverage/17.6.3/build/netstandard2.0/Microsoft.CodeCoverage.targets(23,5): warning MSB3026: Could not copy "/build/tmp.VOjlax5fnd/.nuget/packages/microsoft.codecoverage/17.6.3/build/netstandard2.0/CodeCoverage/amd64/msdia140.dll" to "/nix/store/zjkrxvzzw3az0y4l395p8j9a9pfnry4k-nethermind-1.21.0/lib/nethermind/CodeCoverage/amd64/msdia140.dll". Beginning retry 1 in 1000ms. The process cannot access the file '/nix/store/zjkrxvzzw3az0y4l395p8j9a9pfnry4k-nethermind-1.21.0/lib/nethermind/CodeCoverage/amd64/msdia140.dll' because it is being used by another process.  [/build/source/src/Nethermind/Nethermind.Ethash.Test/Nethermind.Ethash.Test.csproj]
/build/tmp.VOjlax5fnd/.nuget/packages/microsoft.codecoverage/17.6.3/build/netstandard2.0/Microsoft.CodeCoverage.targets(23,5): warning MSB3026: Could not copy "/build/tmp.VOjlax5fnd/.nuget/packages/microsoft.codecoverage/17.6.3/build/netstandard2.0/CodeCoverage/amd64/VanguardInstrumentationProfiler_x64.config" to "/nix/store/zjkrxvzzw3az0y4l395p8j9a9pfnry4k-nethermind-1.21.0/lib/nethermind/CodeCoverage/amd64/VanguardInstrumentationProfiler_x64.config". Beginning retry 1 in 1000ms. The process cannot access the file '/nix/store/zjkrxvzzw3az0y4l395p8j9a9pfnry4k-nethermind-1.21.0/lib/nethermind/CodeCoverage/amd64/VanguardInstrumentationProfiler_x64.config' because it is being used by another process.  [/build/source/src/Nethermind/Nethermind.Ethash.Test/Nethermind.Ethash.Test.csproj]
  Nethermind.Config.Test -> /nix/store/zjkrxvzzw3az0y4l395p8j9a9pfnry4k-nethermind-1.21.0/lib/nethermind/
  Nethermind.Network.Test -> /nix/store/zjkrxvzzw3az0y4l395p8j9a9pfnry4k-nethermind-1.21.0/lib/nethermind/
  Nethermind.UPnP.Plugin -> /nix/store/zjkrxvzzw3az0y4l395p8j9a9pfnry4k-nethermind-1.21.0/lib/nethermind/
  Nethermind.Facade.Test -> /nix/store/zjkrxvzzw3az0y4l395p8j9a9pfnry4k-nethermind-1.21.0/lib/nethermind/
  Nethermind.Network.Discovery.Test -> /nix/store/zjkrxvzzw3az0y4l395p8j9a9pfnry4k-nethermind-1.21.0/lib/nethermind/
  Nethermind.Evm.Test -> /nix/store/zjkrxvzzw3az0y4l395p8j9a9pfnry4k-nethermind-1.21.0/lib/nethermind/
  Nethermind.Wallet -> /nix/store/zjkrxvzzw3az0y4l395p8j9a9pfnry4k-nethermind-1.21.0/lib/nethermind/
  Nethermind.JsonRpc.Test -> /nix/store/zjkrxvzzw3az0y4l395p8j9a9pfnry4k-nethermind-1.21.0/lib/nethermind/
  Nethermind.Merge.Plugin -> /nix/store/zjkrxvzzw3az0y4l395p8j9a9pfnry4k-nethermind-1.21.0/lib/nethermind/
  Nethermind.Consensus -> /nix/store/zjkrxvzzw3az0y4l395p8j9a9pfnry4k-nethermind-1.21.0/lib/nethermind/
  Nethermind.Abi.Test -> /nix/store/zjkrxvzzw3az0y4l395p8j9a9pfnry4k-nethermind-1.21.0/lib/nethermind/
  Nethermind.Blockchain.Test -> /nix/store/zjkrxvzzw3az0y4l395p8j9a9pfnry4k-nethermind-1.21.0/lib/nethermind/
  Nethermind.HealthChecks.Test -> /nix/store/zjkrxvzzw3az0y4l395p8j9a9pfnry4k-nethermind-1.21.0/lib/nethermind/
  Nethermind.Consensus.Test -> /nix/store/zjkrxvzzw3az0y4l395p8j9a9pfnry4k-nethermind-1.21.0/lib/nethermind/
  Nethermind.EthStats -> /nix/store/zjkrxvzzw3az0y4l395p8j9a9pfnry4k-nethermind-1.21.0/lib/nethermind/
  Nethermind.Analytics -> /nix/store/zjkrxvzzw3az0y4l395p8j9a9pfnry4k-nethermind-1.21.0/lib/nethermind/
  Nethermind.Db.Test -> /nix/store/zjkrxvzzw3az0y4l395p8j9a9pfnry4k-nethermind-1.21.0/lib/nethermind/
  Nethermind.AuRa.Test -> /nix/store/zjkrxvzzw3az0y4l395p8j9a9pfnry4k-nethermind-1.21.0/lib/nethermind/
  Nethermind.Cli.Test -> /nix/store/zjkrxvzzw3az0y4l395p8j9a9pfnry4k-nethermind-1.21.0/lib/nethermind/
/build/tmp.VOjlax5fnd/.nuget/packages/microsoft.codecoverage/17.6.3/build/netstandard2.0/Microsoft.CodeCoverage.targets(23,5): warning MSB3026: Could not copy "/build/tmp.VOjlax5fnd/.nuget/packages/microsoft.codecoverage/17.6.3/build/netstandard2.0/InstrumentationEngine/x64/MicrosoftInstrumentationEngine_x64.dll" to "/nix/store/zjkrxvzzw3az0y4l395p8j9a9pfnry4k-nethermind-1.21.0/lib/nethermind/InstrumentationEngine/x64/MicrosoftInstrumentationEngine_x64.dll". Beginning retry 1 in 1000ms. The process cannot access the file '/nix/store/zjkrxvzzw3az0y4l395p8j9a9pfnry4k-nethermind-1.21.0/lib/nethermind/InstrumentationEngine/x64/MicrosoftInstrumentationEngine_x64.dll' because it is being used by another process.  [/build/source/src/Nethermind/Nethermind.Core.Test/Nethermind.Core.Test.csproj]
  Nethermind.State.Test -> /nix/store/zjkrxvzzw3az0y4l395p8j9a9pfnry4k-nethermind-1.21.0/lib/nethermind/
  Nethermind.Ethash.Test -> /nix/store/zjkrxvzzw3az0y4l395p8j9a9pfnry4k-nethermind-1.21.0/lib/nethermind/
  Nethermind.Wallet.Test -> /nix/store/zjkrxvzzw3az0y4l395p8j9a9pfnry4k-nethermind-1.21.0/lib/nethermind/
  Nethermind.Core.Test -> /nix/store/zjkrxvzzw3az0y4l395p8j9a9pfnry4k-nethermind-1.21.0/lib/nethermind/
```

Still investigating root cause...

**Comment by selfuryon** [comment]
Hooray, build is working, need to fix only tests

**Comment by selfuryon** [comment]
Finally, it works :)

**Review by aldoborrero — APPROVED** [review]

**Pull request merged**
