### PR TITLE
Add mev-boost module

### PR DESCRIPTION
**Pull request by aldoborrero**
Introduces mev-boost nixos module

### CODE REVIEW

**Review by brianmcgee — CHANGES_REQUESTED** [review]
Can you add a quick startup test like with Geth, it should help to avoid obvious broken packages.

**Comment by aldoborrero** [comment]
Will do

**Comment by selfuryon** [comment]
@aldoborrero What do you think to use `freeformType` ([link](https://nixos.org/manual/nixos/stable/#sec-freeform-modules)) for args (and maybe something else) in all modules? It allows using undeclared parameters too. I found one example: nix daemon module ([usage](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/nixos/modules/services/misc/nix-daemon.nix#L473), [declaration](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/nixos/modules/services/misc/nix-daemon.nix#L95))

**Comment by aldoborrero** [comment]
@selfuryon nice discovery, let's give it a try! 

Let's make sure though we beef up the tests and also if we can simplify some logic in the process.

**Comment by aldoborrero** [comment]
I'll add the `freeformType` support in another PR as it will touch multiple files.

**Review by selfuryon — APPROVED** [review]
LGTM

**Review by brianmcgee — APPROVED** [review]
LGTM

**Pull request merged**
