### PR TITLE
flake: remove dependency on mynixpkgs

### PR DESCRIPTION
**Pull request by zimbatm**
I ported a bunch of the packages over to keep this project's flake.lock
reasonable in size.

### CODE REVIEW

**Comment by aldoborrero** [comment]
@zimbatm how do you determine reasonably the size and the impact of each input in a flake? I know the mantra of the less the better in terms of the evaluation but is there any tool to properly measure the impact?

For this particular case, I don't like to introduce those packages that don't belong strictly to Ethereum.nix, said that there are other quick wins like removing `flake-root` input and we can continue the work I've made on the issue #258

**Comment by zimbatm** [comment]
I don't think there is necessarily a correct answer; it depends on how you weigh things.

What I noticed is that ethereum.nix pulls all of mynixpkgs but only uses a very small subset of it. Also mynixpkgs only has a single maintainer. That means that coordinating package updates between both repos creates more overhead for maintenance. In that case, my preference is to vendor things. Especially if the idea is that those packages will be in nixpkgs eventually.

**Comment by aldoborrero** [comment]
@zimbatm let's put effort into upstreaming those packages directly to `nixpkgs` instead if you don't mind. I think they are valuable as they are related to `mkdocs` and are useful plugins.

**Comment by zimbatm** [comment]
https://github.com/NixOS/nixpkgs/pull/285561

**Comment by aldoborrero** [comment]
@zimbatm I'm closing this PR as we will have soon the new packages available on `nixpkgs`.

**Pull request closed without merging**
