### PR TITLE
woke: init at v3.2.6

### LINKED ISSUE #216: Add support for woke
Woke is [a new testing framework for Solidity development](https://github.com/Ackee-Blockchain/woke), that includes a Solidity LSP that goes well with VSCode and [Tools for Solidity](https://github.com/Ackee-Blockchain/tools-for-solidity-vscode) extension.

### PR DESCRIPTION
**Pull request by aldoborrero**
Closes #216

### CODE REVIEW

**Comment by aldoborrero** [comment]
Hi, @Nebucatnetzer would you be so kind as to help me to package this Python app? 

I know you have more experience with Nix and Python than I do (which I'm completely ignorant of). Of course, feel free to say no if you don't want to, don't feel obligated :)

**Comment by Nebucatnetzer** [comment]
I can try but I feel far from confident in this area. I’m mostly just hammering it together until it works😅. On 28 Apr 2023, at 12:58, Aldo ***@***.***> wrote:﻿
Hi, @Nebucatnetzer would you be so kind as to help me to package this Python app?
I know you have more experience with Nix and Python than I do (which I'm completely ignorant of). Of course, feel free to say no if you don't want to, don't feel obligated :)

**Comment by Nebucatnetzer** [comment]
Currently I got this flake which goes until pillow and then crashes with the following error.
I first tried to build it directly in this project but I didn't quite understand how things fit together and constantly got recursion errors.
Therefore I just cloned the woke repo and started inside of that.

One dependency I couldn't build is `pywin32` but I at the moment I don't understand why it even tries to build it, if it is marked for win32:
To get moving I commented it out, maybe there is a way to ignore such packages.
https://github.com/Ackee-Blockchain/woke/blob/v3.2.0/pyproject.toml#L34

As for pillow It might be possible to use woke without pillow since it's marked as optional in pyproject.toml.
At least it builds when you add `extras = [ ];` to `mkPoetryApplication`.

I hope this helps a bit :)

**Pillow error**

```
/nix/store/23pbw8pwzlhyl3d3pvl1kl1hx0vgxyyy-pip-install-hook/nix-support/setup-hook: line 13: pushd: dist: No such file or directory
```

**flake.nix**

```
{
  description = "Application packaged using poetry2nix";

  inputs.flake-utils.url = "github:numtide/flake-utils";
  inputs.nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
  inputs.poetry2nix = {
    url = "github:nix-community/poetry2nix";
    inputs.nixpkgs.follows = "nixpkgs";
  };

  outputs = { self, nixpkgs, flake-utils, poetry2nix }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        # see https://github.com/nix-community/poetry2nix/tree/master#api for more functions and examples.
        inherit (poetry2nix.legacyPackages.${system}) mkPoetryApplication defaultPoetryOverrides;
        pkgs = nixpkgs.legacyPackages.${system};
      in
      {
        packages = {
          woke = mkPoetryApplication {
            projectDir = ./.;
            overrides = defaultPoetryOverrides.extend
              (self: super: {
                abch-tree-sitter-solidity = super.abch-tree-sitter-solidity.overridePythonAttrs
                  (
                    old: {
                      buildInputs = (old.buildInputs or [ ]) ++ [ super.setuptools ];
                    }
                  );
                abch-tree-sitter = super.abch-tree-sitter.overridePythonAttrs
                  (
                    old: {
                      buildInputs = (old.buildInputs or [ ]) ++ [ super.setuptools ];
                    }
                  );
                rich-click = super.rich-click.overridePythonAttrs
                  (
                    old: {
                      buildInputs = (old.buildInputs or [ ]) ++ [ super.setuptools ];
                    }
                  );
                griffe = super.griffe.overridePythonAttrs
                  (
                    old: {
                      buildInputs = (old.buildInputs or [ ]) ++ [ super.pdm-backend ];
                    }
                  );
                mkdocs-material = super.mkdocs-material.overridePythonAttrs
                  (
                    old: {
                      buildInputs = (old.buildInputs or [ ]) ++ [ super.hatch-requirements-txt ];
                    }
                  );
                mkdocstrings-python = super.mkdocstrings-python.overridePythonAttrs
                  (
                    old: {
                      buildInputs = (old.buildInputs or [ ]) ++ [ super.pdm-pep517 super.pdm-backend ];
                    }
                  );
                pillow = super.pillow.overridePythonAttrs
                  (
                    old: {
                      nativeBuildInputs = [
                        pkgs.zlib
                      ];
                    }
                  );
              });
          };
          default = self.packages.${system}.woke;
        };
        devShells.default = pkgs.mkShell {
          packages = [ self.packages.${system}.woke ];
        };
      });
}
```

**Comment by aldoborrero** [comment]
@Nebucatnetzer thanks! Since July I have become stronger with my knowledge on packaging Python apps! But basically taking your work, I've added support to the tool.

For now, I've just kept disabling the "*" to only build the basic not fancy build (there's a security CVE warning if I enable it, I'll have a look properly in a couple of days).

Thanks!

**Pull request merged**
