### PR TITLE
chore(github-actions): lighthouse and mev-boost-builder things

### LINKED ISSUE #218: updateFlakePackages action is failing
See the latest run here: https://github.com/nix-community/ethereum.nix/actions/runs/4730426413/jobs/8394121838

### PR DESCRIPTION
**Pull request by selfuryon**
What I did:
* I saw a new stable lighthouse release so I return lighthouse to auto-update (remove it from blacklist)
* I saw a `mev-boost-builder` build error, need to investigate, so I add it to blacklist until I fix its build (#223)
* Update `update-flake-lock` actions to the latest
* Fix latest nethermind build

Close #218

### CODE REVIEW

**Comment by selfuryon** [comment]
Need to fix the latest lighthouse version build too...

**Comment by selfuryon** [comment]
Added a postgresql as a dependency to lighthouse to build that, I think it's temporary. Got that from [discord](https://discord.com/channels/605577013327167508/607025769335750656/1099105607715397662).

**Comment by selfuryon** [comment]
[Found out](https://discord.com/channels/605577013327167508/607025769335750656/1099837876017037404) why Postgres is needed, fixed that by specifying the package we want to build

**Review by brianmcgee — APPROVED** [review]
LGTM

**Pull request merged**
