### PR TITLE
reth: 0.1.0-alpha.13 -> 0.1.0-alpha.16

### PR DESCRIPTION
**Pull request by mitchmindtree**
Also removes some redundant deps and switches to `callPackageUnstable` as the latest `reth` requires rust `1.75`.

### CODE REVIEW

**Review by brianmcgee — DISMISSED** [review]
LGTM

**Comment by brianmcgee** [comment]
@mitchmindtree when bumping versions we try to use a pattern for the commit message: `reth: 0.1.0-alpha.13 -> 0.1.0-alpha.16`

@mergifyio queue

**Comment by mitchmindtree** [comment]
Cheers for the heads up, fixed!

**Comment by mitchmindtree** [comment]
It seems there's an issue with `x86_64-darwin` related to `jemalloc`. I've changed platforms to just include `x86_64-linux`, `aarch64-linux` and `aarch64-darwin` (rather than `platforms.unix`) and added a note.

**Review by brianmcgee — APPROVED** [review]
lgtm

**Pull request merged**
