### PR TITLE
Move repo to nixpkgs-24.05

### PR DESCRIPTION
**Pull request by catwith1hat**
Here is a set of commits that moves the repo to nixpkgs-24.05.

* ssvnode: It iss stuck on Go 1.20 because of its quic-go dependency.
* mev--boost-prysm points to an archived GitHub repo, so I removed that package. 
* geth/erigon: Both surprisingly required new vendor hashes for their go modules. I presume that's because the Go compiler changed. But at the same time many other Go programs in this repo didn't require that. So I am a bit puzzled. 
* sedge/rotki-bin: Fails to compiled. Didn't look into it and I just pinned it to 23.11. Can be fixed later.

Feedback welcome.

### CODE REVIEW

**Comment by catwith1hat** [comment]
I finally found, why `nix flake check` failed and fixed the underlying issue (the overlay definition commit).

@aldoborrero @selfuryon Could you give some feedback? Thanks!

**Comment by catwith1hat** [comment]
No rush. I just wanted to make sure that nobody else is working it :).

**Comment by aldoborrero** [comment]
@catwith1hat again apologies with the delay. I executed `nix flake check` on this branch:

```
framework :: Dev/nix-community/ethereum.nix ‹bump2405› % nix flake check                                                                                                                                                                                                                                                                                                                   1 ↵
error: hash mismatch in fixed-output derivation '/nix/store/kdww16w2ql6x4qa8kp8c95cvvx97v4zp-erigon-2.60.0-go-modules.drv':
         specified: sha256-uOUnUvP0fhNYWSfICkqJV8aMI2f0017baP58VedPov4=
            got:    sha256-38NmSSK3a70WvhZAZ529wdAMlEuk8/4YqtadoLOn1IY=
error: 1 dependencies of derivation '/nix/store/pdhhw667xfnjyh3ypbx45s6imslpqbdl-erigon-2.60.0.drv' failed to build
error (ignored): error: cannot unlink '/tmp/nix-build-reth-0.2.0-beta.6.drv-1/build': Directory not empty
error (ignored): error: cannot unlink '/tmp/nix-build-nethermind-1.25.4.drv-1/build/tmp.cNaOSZoAQS/.nuget/packages': Directory not empty
error (ignored): error: cannot unlink '/tmp/nix-build-heimdall-0.7.3.drv-1/build/source/target/release/deps': Directory not empty
error (ignored): error: cannot unlink '/tmp/nix-build-foundry-nightly-0688b5a.drv-1/build/source/target/release/deps': Directory not empty
error (ignored): error: cannot unlink '/tmp/nix-build-builder-1.11.5-0.3.0.drv-1/build/go-cache': Directory not empty
error: build of '/nix/store/0vxps0k5h1gsq4f0vq8m96a7cwv1vhms-eth2-testnet-genesis-0.9.0.drv', '/nix/store/11a7fq4gy1sgmzhfigxh28h2sfqrj1yx-geth-1.14.3.drv', '/nix/store/7i3m3hzhq4brr9zc2h6gjc8ckc43lz33-lighthouse-5.1.3.drv', '/nix/store/82hmcx95hn0yzpgpx6f8apv4d0ggb5am-nimbus-eth2-24.6.0.drv', '/nix/store/b03iv5fmx4r8i47hjgbamdnpxgh0w6d2-mev-boost-relay-0.29.1.drv', '/nix/store/hs78pp4vgdfcs031rlx1yd63m701a4j0-dreamboat-0.4.20.drv', '/nix/store/i99i6l8gdmxn5gplxkcga4cjldh01795-nethermind-1.25.4.drv', '/nix/store/kywcacamv0nkxbvng6ly74nx3l8w5iis-mev-rs-0.3.0.drv', '/nix/store/kzck3n6jli97fpcdpjm3qjzdjh4ndfiv-reth-0.2.0-beta.6.drv', '/nix/store/lq995p78irkd5357dqdni79j7xg75k07-mev-boost-1.7.drv', '/nix/store/pdhhw667xfnjyh3ypbx45s6imslpqbdl-erigon-2.60.0.drv', '/nix/store/q5lsk8zkdyw295z3amrksk6p6fpvzdy5-heimdall-0.7.3.drv', '/nix/store/rvk6gqi2l3k9y0qrjm9nimdfpsasxd7y-builder-1.11.5-0.3.0.drv', '/nix/store/x0fnzr3cx330l70bnnm6py5hy76lhcb0-foundry-nightly-0688b5a.drv' failed
```

Maybe, some of the commits can be cherry-picked and incorporated into separate PRs and we can incorporate them faster whilst we're still solving all of the remaining issues:

- @catwith1hat
[Remove mdDoc treewide, as it is a deprecated option](https://github.com/nix-community/ethereum.nix/pull/523/commits/63df9672756704318a65c5ef755e4b8c99e684fd)
- [mev-boost-prysm: Remove because of upstream deprecation.](https://github.com/nix-community/ethereum.nix/pull/523/commits/420752de20c9bd4f6f8dd9411f16157cda602a9e)
- @catwith1hat
[Make overlay definition fail gracefully for unknown systems](https://github.com/nix-community/ethereum.nix/pull/523/commits/be0ed0c943336a5b24afcab60e100a607dd6c720)

**Comment by cryptix** [comment]
Trying to pull up ssvnode over here: https://github.com/ssvlabs/ssv/pull/1478

**Comment by catwith1hat** [comment]
Please retry. Somehow the updates break the hashes of erigon/geth.

**Review by aldoborrero — APPROVED** [review]
@catwith1hat thanks for taking the lead. LGTM.

**Pull request merged**
